In [1]:
import numpy as np
import torch
import torch.nn as nn

In [93]:
input_D = 10 # input vector dimension
Attention_D =9 # attention dim
set_num = 6 #number set
head = 3#number of head
batch = 2

In [130]:
Wq = torch.rand(input_D, Attention_D)
Wk = torch.rand(input_D, Attention_D)
Wv = torch.rand(input_D, Attention_D)

## Input

In [131]:
x1 = torch.rand(1,input_D) # shape
x2 = torch.rand(1,input_D)
x3 = torch.rand(1,input_D)
x4 = torch.rand(1,input_D)
x5 = torch.rand(1,input_D)
x6 = torch.rand(1,input_D)

In [132]:
'''

x1_2 = torch.rand(1,input_D)
x2_2 = torch.rand(1,input_D)
x3_2 = torch.rand(1,input_D)
x4_2 = torch.rand(1,input_D)
x5_2 = torch.rand(1,input_D)
x6_2 = torch.rand(1,input_D)

'''


'\n\nx1_2 = torch.rand(1,input_D)\nx2_2 = torch.rand(1,input_D)\nx3_2 = torch.rand(1,input_D)\nx4_2 = torch.rand(1,input_D)\nx5_2 = torch.rand(1,input_D)\nx6_2 = torch.rand(1,input_D)\n\n'

# Q

In [133]:
q1 = x1.mm(Wq) # shape (1, Attention_D)
q2 = x2.mm(Wq) # shape (1, Attention_D)
q3 = x3.mm(Wq) # shape (1, Attention_D)
q4 = x4.mm(Wq) # shape (1, Attention_D)
q5 = x5.mm(Wq) # shape (1, Attention_D)
q6 = x6.mm(Wq) # shape (1, Attention_D)


In [134]:
q1.size()

torch.Size([1, 9])

# K

In [135]:
k1 = x1.mm(Wk) # shape (1, Attention_D)
k2 = x2.mm(Wk) # shape (1, Attention_D)
k3 = x3.mm(Wk) # shape (1, Attention_D)
k4 = x4.mm(Wk) # shape (1, Attention_D)
k5 = x5.mm(Wk) # shape (1, Attention_D)
k6 = x6.mm(Wk) # shape (1, Attention_D)


# V

In [136]:
v1 = x1.mm(Wv) # shape (1, Attention_D)
v2 = x2.mm(Wv) # shape (1, Attention_D)
v3 = x3.mm(Wv) # shape (1, Attention_D)
v4 = x4.mm(Wv) # shape (1, Attention_D)
v5 = x5.mm(Wv) # shape (1, Attention_D)
v6 = x6.mm(Wv) # shape (1, Attention_D)


## Score

In [137]:
K = torch.cat([k1,k2,k3,k4,k5,k6])  # shape (set_num, Attention_D)

In [138]:
score1 = q1.mm(K.T) # shape (1, set_num)
score2 = q2.mm(K.T) # shape (1, set_num)
score3 = q3.mm(K.T) # shape (1, set_num)
score4 = q4.mm(K.T) # shape (1, set_num)
score5 = q5.mm(K.T) # shape (1, set_num)
score6 = q6.mm(K.T) # shape (1, set_num)


In [139]:
score1 = torch.softmax(score1,1) # shape (1, set_num)
score2 = torch.softmax(score2,1) # shape (1, set_num)
score3 = torch.softmax(score3,1) # shape (1, set_num)
score4 = torch.softmax(score4,1) # shape (1, set_num)
score5 = torch.softmax(score5,1) # shape (1, set_num)
score6 = torch.softmax(score6,1) # shape (1, set_num)

In [140]:
V = torch.cat([v1,v2,v3,v4,v5,v6])  # shape (set_num, Attention_D)

In [141]:
y1 = score1.mm(V)  # shape (1, Attention_D)
y2 = score2.mm(V)  # shape (set_num, Attention_D)
y3 = score3.mm(V)  # shape (set_num, Attention_D)
y4 = score4.mm(V)  # shape (set_num, Attention_D)
y5 = score5.mm(V)  # shape (set_num, Attention_D)
y6 = score6.mm(V)  # shape (set_num, Attention_D)

# Matrix computation

In [142]:
X = torch.cat([x1,x2,x3,x4,x5,x6])  # shape (set_num, input_D)

In [143]:
X.size()

torch.Size([6, 10])

In [144]:
q = X.mm(Wq)
k = X.mm(Wk)
v = X.mm(Wv)

In [145]:
q[0], q1

(tensor([3.5973, 2.7658, 2.7146, 2.7979, 2.4993, 2.9534, 2.0550, 3.3966, 2.3335]),
 tensor([[3.5973, 2.7658, 2.7146, 2.7979, 2.4993, 2.9534, 2.0550, 3.3966, 2.3335]]))

In [146]:
score = q.mm(k.T)
score = torch.softmax(score,1)

(tensor([[5.6879e-02, 1.8503e-16, 1.3087e-01, 8.1225e-01, 4.1391e-07, 3.1919e-14]]),
 tensor([5.6878e-02, 1.8503e-16, 1.3087e-01, 8.1225e-01, 4.1391e-07, 3.1919e-14]))

In [24]:
score

tensor([[1.1469e-07, 3.0884e-02, 3.0552e-04, 6.2617e-03, 7.3556e-05, 9.6247e-01],
        [5.5488e-10, 6.8860e-03, 2.0548e-05, 1.2909e-03, 3.6430e-06, 9.9180e-01],
        [4.9558e-09, 1.4388e-02, 5.5425e-05, 2.2625e-03, 1.0352e-05, 9.8328e-01],
        [5.1409e-09, 1.0453e-02, 7.9062e-05, 2.1880e-03, 1.0400e-05, 9.8727e-01],
        [5.0904e-08, 2.0102e-02, 1.8867e-04, 5.2869e-03, 3.5003e-05, 9.7439e-01],
        [7.1500e-10, 6.9585e-03, 3.0594e-05, 1.0318e-03, 3.0887e-06, 9.9198e-01]])

In [25]:
y = score.mm(v)

In [26]:
y

tensor([[2.7022, 2.5275, 3.6328, 3.2796, 2.8994, 3.4103, 3.7051, 1.9040, 2.8176],
        [2.6976, 2.5168, 3.6393, 3.2885, 2.9009, 3.4249, 3.7011, 1.8985, 2.8109],
        [2.6990, 2.5199, 3.6376, 3.2860, 2.9005, 3.4207, 3.7023, 1.9000, 2.8131],
        [2.6983, 2.5184, 3.6383, 3.2871, 2.9006, 3.4226, 3.7017, 1.8994, 2.8119],
        [2.7003, 2.5232, 3.6350, 3.2831, 2.8999, 3.4161, 3.7036, 1.9020, 2.8146],
        [2.6975, 2.5167, 3.6394, 3.2886, 2.9009, 3.4250, 3.7011, 1.8984, 2.8110]])

# BAtch

In [70]:
X = torch.rand(batch, set_num, input_D)

In [71]:
Wq = torch.rand(input_D, Attention_D)
Wk = torch.rand(input_D, Attention_D)
Wv = torch.rand(input_D, Attention_D)

In [72]:
q = X.matmul(Wq)
k = X.matmul(Wk)
v = X.matmul(Wv)

In [73]:
q.size()

torch.Size([2, 6, 9])

In [74]:
score = q.matmul(k.transpose(1,2))

In [75]:
torch.softmax(score,2)

tensor([[[4.8460e-03, 8.7489e-05, 1.3373e-06, 4.6390e-05, 9.9502e-01,
          4.9059e-12],
         [3.2509e-03, 3.0859e-05, 4.5620e-07, 3.3855e-05, 9.9668e-01,
          6.8077e-13],
         [4.2192e-03, 4.8509e-05, 8.7214e-07, 4.5282e-05, 9.9569e-01,
          2.5088e-12],
         [6.9801e-03, 2.8522e-04, 5.1052e-06, 1.4196e-04, 9.9259e-01,
          3.2233e-11],
         [1.6680e-03, 1.2755e-05, 8.5861e-08, 8.7429e-06, 9.9831e-01,
          2.8383e-14],
         [4.3279e-02, 5.0912e-03, 3.8429e-04, 2.9784e-03, 9.4827e-01,
          1.8925e-07]],

        [[9.8799e-01, 4.2880e-08, 1.2012e-02, 5.4158e-19, 8.2922e-10,
          8.8250e-09],
         [9.8309e-01, 1.4208e-07, 1.6912e-02, 1.0228e-17, 3.1811e-09,
          4.7969e-08],
         [9.8604e-01, 1.0392e-07, 1.3961e-02, 8.7375e-18, 2.4350e-09,
          3.1803e-08],
         [9.2276e-01, 8.0913e-05, 7.7110e-02, 7.2312e-11, 6.7805e-06,
          4.4309e-05],
         [9.7963e-01, 1.4062e-06, 2.0365e-02, 4.0259e-15, 5.9999e-08

# Head

In [77]:
X = torch.rand(batch, set_num, input_D)

In [78]:
Wq = torch.rand(input_D, Attention_D * head)
Wk = torch.rand(input_D, Attention_D * head)
Wv = torch.rand(input_D, Attention_D * head)

In [79]:
q = X.matmul(Wq)
k = X.matmul(Wk)
v = X.matmul(Wv)

In [80]:
q_view = q.view(b,s,h,m).transpose(1,2)
k_view = k.view(b,s,h,m).transpose(1,2)
v_view = v.view(b,s,h,m).transpose(1,2)

In [81]:
score = q_view.matmul(k_view.transpose(2,3))

In [82]:
score.size()

torch.Size([2, 3, 6, 6])

In [83]:
y = score.matmul(v_view)